import React, { createContext, useContext, useState } from 'react';

type Language = 'pt' | 'en';

interface LanguageContextType {
    language: Language;
    setLanguage: (lang: Language) => void;
    t: (key: string) => string;
}

const translations = {
    pt: {
        'profile.title': 'Meu Perfil',
        'profile.edit': 'Editar Perfil',
        'profile.history': 'Histórico de Viagens',
        'profile.payments': 'Métodos de Pagamento',
        'profile.settings': 'Configurações',
        'settings.darkMode': 'Modo Escuro',
        'settings.darkModeDesc': 'Alternar tema do App',
        'settings.language': 'Idioma',
        'settings.notifications': 'Notificações',
        'settings.deleteAccount': 'Apagar Conta',
        'common.save': 'Salvar Alterações',
        'common.back': 'Voltar',
        'common.continue': 'Continuar',
        'common.cancel': 'Cancelar',
        'common.attention': 'Atenção',
        'common.login': 'Entrar',
        'common.back_to_home': 'Voltar ao Início',
        'common.app_tagline': 'QUELIMOVE v2.6 - QUALIDADE E MOVIMENTO',
        'common.file_selected': 'Ficheiro selecionado',
        'common.click_to_upload': 'Clique para carregar',
        'driver.dash.greeting': 'Olá, ',
        'driver.dash.online': 'Em Trabalho',
        'driver.dash.offline': 'Descansando',
        'driver.dash.balance': 'Saldo',
        'driver.dash.analysis.title': 'Quase Lá! CONTA EM ANÁLISE',
        'driver.dash.analysis.desc': 'Obrigado pelo registo! 🚀 Os teus dados estão com o Admin Mansur.',
        'driver.dash.analysis.whatsapp': 'Ativar no WhatsApp',
        'driver.dash.analysis.preview': 'Ver Mapa (Modo Prévia)',
        'driver.dash.ride.new': 'Novo Pedido',
        'driver.dash.ride.in_progress': 'Em Curso',
        'driver.dash.ride.pickup': 'Recolha',
        'driver.dash.ride.destination': 'Destino',
        'driver.dash.ride.refuse': 'Recusar',
        'driver.dash.ride.accept': 'ACEITAR',
        'driver.dash.ride.call': 'Ligar Cliente',
        'driver.dash.ride.nav': 'Navegação',
        'driver.dash.ride.arrived': 'CHEGUEI AO LOCAL',
        'driver.dash.ride.notify_arrival': 'AVISAR CHEGADA',
        'driver.dash.ride.start': 'INICIAR VIAGEM',
        'driver.dash.ride.finish': 'FINALIZAR VIAGEM',
        'driver.dash.ride.cancelled_by_client': 'A viagen foi cancelada pelo cliente.',
        'driver.dash.status.searching': 'À Procura...',
        'driver.dash.status.offline': 'Estás Offline',
        'driver.dash.status.active_rides': 'Pedidos ativos na zona',
        'driver.dash.status.go_online': 'Fica online para faturar',
        'driver.dash.summary.title': 'Viagem Concluída!',
        'driver.dash.summary.earnings': 'Teus Ganhos (85%)',
        'driver.dash.summary.total': 'Total da Viagem',
        'driver.dash.summary.fee': 'Taxa Quelimove (15%)',
        'driver.reg.title': 'Cadastro Motorista',
        'driver.reg.register_title': 'Cadastro Motorista',
        'driver.reg.login_title': 'Login Motorista',
        'driver.reg.welcome_back': 'Bem-vindo de volta',
        'driver.reg.login_desc': 'Entre com seu telefone e senha para acessar.',
        'driver.reg.phone': 'WhatsApp / Telefone',
        'driver.reg.password': 'Palavra-passe',
        'driver.reg.login_btn': 'Entrar Agora',
        'driver.reg.create_acc': 'Criar Nova Conta',
        'driver.reg.fill_phone_password': 'Por favor, preencha o telefone e a senha.',
        'driver.reg.account_pending_blocked': 'Sua conta está em análise ou foi bloqueada. Contacte o suporte.',
        'driver.reg.not_driver_account': 'Conta não é de motorista.',
        'driver.reg.password_min_length': 'A senha deve ter pelo menos 6 caracteres.',
        'driver.reg.registration_error': 'Erro ao realizar cadastro: ',
        'driver.reg.step1.title': 'Conta e Dados',
        'driver.reg.step1.desc': 'Insira seus dados pessoais para começar.',
        'driver.reg.name': 'Nome Completo',
        'driver.reg.name_placeholder': 'Seu nome',
        'driver.reg.password_choice': 'Escolha uma Senha',
        'driver.reg.password_placeholder': 'Mínimo 6 caracteres',
        'driver.reg.bi': 'Número do BI',
        'driver.reg.bi_placeholder': 'BI...',
        'driver.reg.bi_invalid': 'BI Inválido (12 dígitos + Letra)',
        'driver.reg.underage': 'Deve ter +18 anos',
        'driver.reg.birth': 'Nascimento',
        'driver.reg.step2.title': 'Informação do Veículo',
        'driver.reg.step2.desc': 'Diga-nos o que você conduz.',
        'driver.reg.bairro': 'Bairro de Atuação',
        'driver.reg.select_bairro': 'Selecionar Bairro...',
        'driver.reg.model': 'Marca e Modelo',
        'driver.reg.model_placeholder': 'Ex: Honda Ace 125',
        'driver.reg.plate': 'Matrícula',
        'driver.reg.plate_placeholder': 'ABC-123-MC',
        'driver.reg.color': 'Cor',
        'driver.reg.color_placeholder': 'Vermelha',
        'driver.reg.year': 'Ano',
        'driver.reg.year_placeholder': '2020',
        'driver.reg.step3.title': 'Documentação',
        'driver.reg.step3.desc': 'Carregue fotos legíveis para validação.',
        'driver.reg.doc.bi_front': 'BI (Frente)',
        'driver.reg.doc.bi_back': 'BI (Verso)',
        'driver.reg.doc.license': 'Carta de Condução',
        'driver.reg.doc.profile': 'Sua Foto (Selfie)',
        'driver.reg.doc.vehicle': 'Livrete/Viatura',
        'driver.reg.step4.title': 'Revisar e Finalizar',
        'driver.reg.step4.desc': 'Confirme se tudo está correto.',
        'driver.reg.payment_method': 'Método de Pagamento',
        'driver.reg.cash_only': 'Apenas Dinheiro (Cash)',
        'driver.reg.terms': 'Declaro que as informações acima são verdadeiras e aceito os Termos e Condições da Quelimove para parceiros.',
        'driver.reg.success_title': 'REGISTO RECEBIDO!',
        'driver.reg.success_desc': 'Os teus dados foram enviados para análise. A tua conta está agora',
        'driver.reg.pending_approval': 'Pendente de Aprovação',
        'driver.reg.notify_whatsapp': 'Avisar no WhatsApp',
        'vehicle_type.moto': 'Moto',
        'vehicle_type.txopela': 'Txopela'
    },
    en: {
        'profile.title': 'My Profile',
        'profile.edit': 'Edit Profile',
        'profile.history': 'Ride History',
        'profile.payments': 'Payment Methods',
        'profile.settings': 'Settings',
        'settings.darkMode': 'Dark Mode',
        'settings.darkModeDesc': 'Toggle app theme',
        'settings.language': 'Language',
        'settings.notifications': 'Notifications',
        'settings.deleteAccount': 'Delete Account',
        'common.save': 'Save Changes',
        'common.back': 'Back',
        'common.continue': 'Continue',
        'common.cancel': 'Cancel',
        'common.attention': 'Attention',
        'common.login': 'Log In',
        'common.back_to_home': 'Back to Home',
        'common.app_tagline': 'QUELIMOVE v2.6 - QUALITY AND MOVEMENT',
        'common.file_selected': 'File selected',
        'common.click_to_upload': 'Click to upload',
        'driver.dash.greeting': 'Hello, ',
        'driver.dash.online': 'On Duty',
        'driver.dash.offline': 'Resting',
        'driver.dash.balance': 'Balance',
        'driver.dash.analysis.title': 'Almost There! ACCOUNT UNDER REVIEW',
        'driver.dash.analysis.desc': 'Thanks for registering! 🚀 Your data is with Admin Mansur.',
        'driver.dash.analysis.whatsapp': 'Activate on WhatsApp',
        'driver.dash.analysis.preview': 'View Map (Preview Mode)',
        'driver.dash.ride.new': 'New Request',
        'driver.dash.ride.in_progress': 'In Progress',
        'driver.dash.ride.pickup': 'Pickup',
        'driver.dash.ride.destination': 'Destination',
        'driver.dash.ride.refuse': 'Refuse',
        'driver.dash.ride.accept': 'ACCEPT',
        'driver.dash.ride.call': 'Call Customer',
        'driver.dash.ride.nav': 'Navigation',
        'driver.dash.ride.arrived': 'ARRIVED AT LOCATION',
        'driver.dash.ride.notify_arrival': 'NOTIFY ARRIVAL',
        'driver.dash.ride.start': 'START TRIP',
        'driver.dash.ride.finish': 'FINISH TRIP',
        'driver.dash.ride.cancelled_by_client': 'The trip was cancelled by the client.',
        'driver.dash.status.searching': 'Searching...',
        'driver.dash.status.offline': 'You are Offline',
        'driver.dash.status.active_rides': 'Active requests in the area',
        'driver.dash.status.go_online': 'Go online to start earning',
        'driver.dash.summary.title': 'Trip Completed!',
        'driver.dash.summary.earnings': 'Your Earnings (85%)',
        'driver.dash.summary.total': 'Total Fare',
        'driver.dash.summary.fee': 'Quelimove Fee (15%)',
        'driver.reg.title': 'Driver Registration',
        'driver.reg.register_title': 'Driver Registration',
        'driver.reg.login_title': 'Driver Login',
        'driver.reg.welcome_back': 'Welcome back',
        'driver.reg.login_desc': 'Enter your phone and password to access.',
        'driver.reg.phone': 'WhatsApp / Phone',
        'driver.reg.password': 'Password',
        'driver.reg.login_btn': 'Log In Now',
        'driver.reg.create_acc': 'Create New Account',
        'driver.reg.fill_phone_password': 'Please fill in phone and password.',
        'driver.reg.account_pending_blocked': 'Your account is under review or blocked. Contact support.',
        'driver.reg.not_driver_account': 'Account is not a driver account.',
        'driver.reg.password_min_length': 'Password must be at least 6 characters.',
        'driver.reg.registration_error': 'Error during registration: ',
        'driver.reg.step1.title': 'Account and Data',
        'driver.reg.step1.desc': 'Enter your personal data to begin.',
        'driver.reg.name': 'Full Name',
        'driver.reg.name_placeholder': 'Your name',
        'driver.reg.password_choice': 'Choose a Password',
        'driver.reg.password_placeholder': 'Minimum 6 characters',
        'driver.reg.bi': 'ID Number (BI)',
        'driver.reg.bi_placeholder': 'BI...',
        'driver.reg.bi_invalid': 'Invalid BI (12 digits + Letter)',
        'driver.reg.underage': 'Must be 18+ years old',
        'driver.reg.birth': 'Birthdate',
        'driver.reg.step2.title': 'Vehicle Information',
        'driver.reg.step2.desc': 'Tell us what you drive.',
        'driver.reg.bairro': 'Operation Neighborhood',
        'driver.reg.select_bairro': 'Select Neighborhood...',
        'driver.reg.model': 'Make and Model',
        'driver.reg.model_placeholder': 'Ex: Honda Ace 125',
        'driver.reg.plate': 'License Plate',
        'driver.reg.plate_placeholder': 'ABC-123-MC',
        'driver.reg.color': 'Color',
        'driver.reg.color_placeholder': 'Red',
        'driver.reg.year': 'Year',
        'driver.reg.year_placeholder': '2020',
        'driver.reg.step3.title': 'Documentation',
        'driver.reg.step3.desc': 'Upload legible photos for validation.',
        'driver.reg.doc.bi_front': 'ID (Front)',
        'driver.reg.doc.bi_back': 'ID (Back)',
        'driver.reg.doc.license': 'Driver\'s License',
        'driver.reg.doc.profile': 'Your Photo (Selfie)',
        'driver.reg.doc.vehicle': 'Vehicle Registration',
        'driver.reg.step4.title': 'Review and Finish',
        'driver.reg.step4.desc': 'Confirm if everything is correct.',
        'driver.reg.payment_method': 'Payment Method',
        'driver.reg.cash_only': 'Cash Only',
        'driver.reg.terms': 'I declare that the above information is true and I accept the Terms and Conditions of Quelimove for partners.',
        'driver.reg.success_title': 'REGISTRATION RECEIVED!',
        'driver.reg.success_desc': 'Your data has been sent for analysis. Your account is now',
        'driver.reg.pending_approval': 'Pending Approval',
        'driver.reg.notify_whatsapp': 'Notify on WhatsApp',
        'vehicle_type.moto': 'Moto',
        'vehicle_type.txopela': 'Txopela'
    }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
    const [language, setLanguageState] = useState<Language>(() => {
        return (localStorage.getItem('app_language') as Language) || 'pt';
    });

    const setLanguage = (lang: Language) => {
        setLanguageState(lang);
        localStorage.setItem('app_language', lang);
    };

    const t = (key: string) => {
        return translations[language][key as keyof typeof translations['pt']] || key;
    };

    return (
        <LanguageContext.Provider value={{ language, setLanguage, t }}>
            {children}
        </LanguageContext.Provider>
    );
};

export const useLanguage = () => {
    const context = useContext(LanguageContext);
    if (!context) throw new Error('useLanguage must be used within a LanguageProvider');
    return context;
};
